services: 
  catalog_db: 
    image: docker.io/postgres:15-alpine
    volumes: 
      - catalog_db:/var/lib/postgresql/data/pgdata
    env_file: 
      - .env
    ports:
      - 5434:5432
    networks: 
      - tcc-network

  prestart:
      build:
        context: .
      networks:
        - tcc-network
      depends_on:
        - catalog_db
      command: sh scripts/prestart.sh
      env_file:
        - .env

  catalog_backend: 
    build:
      context: .
    ports: 
      - 8002:8002
    networks:
      - tcc-network
    depends_on: 
      - catalog_db
    env_file: 
      - .env  

volumes: 
  catalog_db:

networks:
  tcc-network: 
    driver: bridge